language: node_js
node_js:
  - "0.10"
  - "node"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ad3892c1b2dcefe48754
    on_success: change
    on_failure: always
    #on_start: false
